services:
  postgres:
    image: postgres:15
    container_name: bookstore_postgres
    restart: always
    environment:
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: bookstore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: bookstore_analytics
      MYSQL_USER: analytics_user
      MYSQL_PASSWORD: analytics_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: bookstore_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: bookstore_jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  mysql_data:
  redis_data:
  jenkins_home: